<a href="https://colab.research.google.com/github/kimve1969/mgu_ds_cours/blob/main/semestr%202.1/task%201/semestr_2_1_task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ВМК МГУ, Курс по Data Science (DS) и Machine Learning (ML) 2026 год
2 семестр, Анализ данных в Python,
Ким Виталий Евгеньевич, ПАО "Сургутнефтегаз"
19.07.2026

Постановка задачи

Будем работать с данными о клиентах банка, который интересуется, произойдет ли просрочка платежа на 90 и более дней при выдаче кредита.

1. Прочтите данные из файла data.csv Функции, которые могут пригодиться при решении: pd.read_csv(..., delimiter=',')
2. Выведите описание прочтенных данных. Функции, которые могут пригодиться при решении: .describe()
3. Отобразите несколько первых и несколько последних записей. Функции, которые могут пригодиться при решении: .head(), .tail() Какие параметры можно передать этим функциям?
4. Прочтите в файле DataDictionary-ru.txt, что означают столбцы матрицы. Какому типу принадлежит каждый столбец (вещественный, целый, категориальный)?
5. Заметьте, что столбец DebtRatio содержит неправдоподобные данные. Только значения, соответствующие известному месячному доходу, являются отношениями. Остальные – абсолютные значения месячных выплат процентов. Исправьте данные, сделав все значения столбца DebtRatio абсолютными (умножьте их на MonthlyIncome). Чтобы ваша программа быстро работала на полных данных, постарайтесь не использовать цикл.
6. Поменяйте имя столбца на Debt. Функции, которые могут пригодиться при решении: .rename(columns= {'староеИмя':'новоеИмя'}, inplace=True)
7. Вычислите средний ежемесячный доход и присвойте всем клиентам с неизвестным доходом полученное число.
8. Используя метод groupby, оцените вероятности невозврата кредита (SeriousDlqin2yrs=1) для различных значений количества иждивенцев (NumberOfDependents). Проделайте аналогичную процедуру для различных значений столбца NumberRealEstateLoansOrLines

# ВЫПОЛНЕНИЕ

In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/kimve1969/mgu_ds_cours/refs/heads/main/semestr%202.1/task%201/data.csv')

df.head(10)

,Id,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
5,6,0,0.213179,74,0,0.375607,3500.0,3,0,1,0,1.0
6,7,0,0.305682,57,0,5710.000000,NaN,8,0,3,0,0.0
7,8,0,0.754464,39,0,0.209940,3500.0,8,0,0,0,0.0
8,9,0,0.116951,27,0,46.000000,NaN,2,0,0,0,NaN
9,10,0,0.189169,57,0,0.606291,23684.0,9,0,4,0,2.0

In [12]:
df.rename(columns={'SeriousDlqin2yrs':'Прогноз просрочки в течении 2 лет',
                   'RevolvingUtilizationOfUnsecuredLines':'% остатка на кред.картах',
                   'age':'возраст',
                   'NumberOfTime30-59DaysPastDueNotWorse':'кол-во просрочек 30-59 дней',
                   'DebtRatio':'% платежей от долга или абс.платеж',
                   'MonthlyIncome':'Месячный доход'}, inplace=True)
df

,Id,Прогноз просрочки в течении 2 лет,% остатка на кред.картах,возраст,кол-во просрочек 30-59 дней,% платежей от долга или абс.платеж,Месячный доход,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1345,1346,0,0.000000,39,0,0.055916,4166.0,5,0,0,0,0.0
1346,1347,0,0.045694,49,0,0.300175,4000.0,14,0,1,0,1.0
1347,1348,0,0.022780,53,0,0.323068,10000.0,14,0,2,0,1.0
1348,1349,0,0.036934,56,0,0.287935,8362.0,8,0,1,0,2.0
1349,1350,0,0.000000,62,0,1463.000000,NaN,5,0,1,0,0.0

In [2]:
df.tail(10)

,Id,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1340,1341,0,0.002428,77,0,0.238471,3165.0,13,0,1,0,0.0
1341,1342,0,0.173949,68,0,3015.000000,NaN,7,0,2,0,0.0
1342,1343,0,0.047198,74,0,0.375672,9305.0,8,0,5,0,8.0
1343,1344,0,0.202775,59,0,6994.000000,NaN,23,0,3,0,2.0
1344,1345,0,0.087406,32,0,0.288978,1750.0,8,0,0,0,2.0
1345,1346,0,0.000000,39,0,0.055916,4166.0,5,0,0,0,0.0
1346,1347,0,0.045694,49,0,0.300175,4000.0,14,0,1,0,1.0
1347,1348,0,0.022780,53,0,0.323068,10000.0,14,0,2,0,1.0
1348,1349,0,0.036934,56,0,0.287935,8362.0,8,0,1,0,2.0
1349,1350,0,0.000000,62,0,1463.000000,NaN,5,0,1,0,0.0

In [11]:
df.describe()

,Id,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1094.000000,1350.000000,1350.000000,1350.000000,1350.000000,1307.000000
mean,675.500000,0.060000,3.577895,52.048889,0.257778,356.123363,6438.473492,8.434074,0.080000,0.986667,0.062222,0.737567
std,389.855743,0.237575,84.914699,15.009875,0.751718,1156.603074,7849.754675,5.129287,0.376634,1.008401,0.306555,1.086949
min,1.000000,0.000000,0.000000,22.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,338.250000,0.000000,0.031140,40.000000,0.000000,0.175125,3300.000000,5.000000,0.000000,0.000000,0.000000,0.000000
50%,675.500000,0.000000,0.156891,52.000000,0.000000,0.367049,5222.500000,8.000000,0.000000,1.000000,0.000000,0.000000
75%,1012.750000,0.000000,0.543145,63.000000,0.000000,0.807001,8055.250000,11.000000,0.000000,2.000000,0.000000,1.000000
max,1350.000000,1.000000,2340.000000,97.000000,10.000000,15466.000000,208333.000000,31.000000,5.000000,8.000000,5.000000,8.000000

### Описание полей дата фрейма

In [10]:
from os import read
import urllib.request

urllib.request.urlretrieve('https://raw.githubusercontent.com/kimve1969/mgu_ds_cours/refs/heads/main/semestr%202.1/task%201/DataDictionary-ru.txt', 'DataDictionary-ru.txt')

with open('DataDictionary-ru.txt','r') as f:
  for line in f:
    line = line.rstrip('\n')
    print(line)

SeriousDlqin2yrs
Произойдет ли просрочка платежа на 90 или более дней в ближайшие 2 года (Y/N)

RevolvingUtilizationOfUnsecuredLines
Процент оставшихся денег на всех кредитных картах   (%)

age
Возраст (integer)

NumberOfTime30-59DaysPastDueNotWorse
Количество кратковременных просрочек платежа (30-59 дней) за последние 2 года   (integer)

DebtRatio
Выплачиваемые в месяц проценты от долга, алименты, бытовые расходы, деленные на месячный доход (если месячный доход неизвестен, то абсолютная величина выплат)  (%)

MonthlyIncome
Месячный доход  (real)

NumberOfOpenCreditLinesAndLoans
Количество кредитов (или кредитных карт) за исключением ипотеки (integer)

NumberOfTimes90DaysLate
Кредитная история: количество серьезных просрочек платежа на 90 дней или более (integer)

NumberRealEstateLoansOrLines
Количество ипотек   (integer)

NumberOfTime60-89DaysPastDueNotWorse
Количество среднесрочных просрочек платежа (60-89 дней) за последние 2 года (integer)

NumberOfDependents
Количество иждивенцев в семье, включая самого клиента   (integer)