<a href="https://colab.research.google.com/github/kimve1969/mgu_ds_cours/blob/main/semestr%202.1/task%203/semestr_2_1_task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ВМК МГУ, Курс по Data Science (DS) и Machine Learning (ML) 2026 год
2 семестр, Анализ данных в Python,
Ким Виталий Евгеньевич, ПАО "Сургутнефтегаз"
22.07.2026

## Задание 3. Разведочный анализ

In [9]:
import pandas as pd
# подготавливаем файлы
!wget -N https://raw.githubusercontent.com/kimve1969/mgu_ds_cours/refs/heads/main/semestr%202.1/task%203/surveys.csv
!wget -N https://raw.githubusercontent.com/kimve1969/mgu_ds_cours/refs/heads/main/semestr%202.1/task%203/species.csv
!wget -N https://raw.githubusercontent.com/kimve1969/mgu_ds_cours/refs/heads/main/semestr%202.1/task%203/plot_location.xlsx

--2026-07-27 17:19:47--  https://raw.githubusercontent.com/kimve1969/mgu_ds_cours/refs/heads/main/semestr%202.1/task%203/surveys.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1478951 (1.4M) [text/plain]
Saving to: ‘surveys.csv’

surveys.csv         100%[===================>]   1.41M  --.-KB/s    in 0.01s

Last-modified header missing -- time-stamps turned off.
2026-07-27 17:19:47 (145 MB/s) - ‘surveys.csv’ saved [1478951/1478951]

--2026-07-27 17:19:47--  https://raw.githubusercontent.com/kimve1969/mgu_ds_cours/refs/heads/main/semestr%202.1/task%203/species.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1671 (1.6K) [text/plain]
Saving to: ‘species.csv’

species.csv         100%[===================>]   1.63K  --.-KB/s    in 0s

Last-modified header missing -- time-stamps turned off.
2026-07-27 17:19:47 (24.4 MB/s) - ‘species.csv’ saved [1671/1671]

--2026-07-27 17:19:47--  https://raw.githubusercontent.com/kimve1969/mgu_ds_cours/refs/heads/main/semestr%202.1/task%203/plot_location.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6353 (6.2K) [application/octet-stream]
Saving to: ‘plot_location.xlsx’

plot_location.xlsx  100%[===================>]   6.20K  --.-KB/s    in 0s

Last-modified header missing -- time-stamps turned off.
2026-07-27 17:19:47 (47.3 MB/s) - ‘plot_location.xlsx’ saved [6353/6353]

# 1. Данные опроса

In [19]:
# считываем данные опроса
surveys_data = pd.read_csv('surveys.csv')
surveys_data

       record_id  month  day  year  plot species sex_char   wgt
0              1      7   16  1977     2     NaN        M   NaN
1              2      7   16  1977     3     NaN        M   NaN
2              3      7   16  1977     2      DM        F   NaN
3              4      7   16  1977     7      DM        M   NaN
4              5      7   16  1977     3      DM        M   NaN
...          ...    ...  ...   ...   ...     ...      ...   ...
35544      35545     12   31  2002    15      AH      NaN   NaN
35545      35546     12   31  2002    15      AH      NaN   NaN
35546      35547     12   31  2002    10      RM        F  14.0
35547      35548     12   31  2002     7      DO        M  51.0
35548      35549     12   31  2002     5     NaN      NaN   NaN

[35549 rows x 8 columns]

In [20]:
# дублирующих записей нет sum()==0
surveys_data.duplicated().sum()

np.int64(0)

In [22]:
surveys_data['datasetname'] = 'Ecological Archives E090-118-D1'
surveys_data

,record_id,month,day,year,plot,species,sex_char,wgt,datasetname
0,1,7,16,1977,2,NaN,M,NaN,Ecological Archives E090-118-D1
1,2,7,16,1977,3,NaN,M,NaN,Ecological Archives E090-118-D1
2,3,7,16,1977,2,DM,F,NaN,Ecological Archives E090-118-D1
3,4,7,16,1977,7,DM,M,NaN,Ecological Archives E090-118-D1
4,5,7,16,1977,3,DM,M,NaN,Ecological Archives E090-118-D1
...,...,...,...,...,...,...,...,...,...
35544,35545,12,31,2002,15,AH,NaN,NaN,Ecological Archives E090-118-D1
35545,35546,12,31,2002,15,AH,NaN,NaN,Ecological Archives E090-118-D1
35546,35547,12,31,2002,10,RM,F,14.0,Ecological Archives E090-118-D1
35547,35548,12,31,2002,7,DO,M,51.0,Ecological Archives E090-118-D1
35548,35549,12,31,2002,5,NaN,NaN,NaN,Ecological Archives E090-118-D1

In [30]:
surveys_data.groupby(by='sex_char').count()

          record_id  month    day   year   plot  species    wgt  datasetname
sex_char
F             15689  15689  15689  15689  15689    15014  15303        15689
M             17348  17348  17348  17348  17348    16846  16879        17348
P                 1      1      1      1      1        1      1            1
R                 3      3      3      3      3        3      0            3
Z                 1      1      1      1      1        1      1            1

In [32]:
from typing_extensions import TypeVarTuple
# сохраняем исходную информацию о поле
surveys_data.rename(columns={'sex_char':'verbatimSex'}, inplace=True)

,record_id,month,day,year,plot,species,verbatimSex,wgt,datasetname
0,1,7,16,1977,2,NaN,M,NaN,Ecological Archives E090-118-D1
1,2,7,16,1977,3,NaN,M,NaN,Ecological Archives E090-118-D1
2,3,7,16,1977,2,DM,F,NaN,Ecological Archives E090-118-D1
3,4,7,16,1977,7,DM,M,NaN,Ecological Archives E090-118-D1
4,5,7,16,1977,3,DM,M,NaN,Ecological Archives E090-118-D1
...,...,...,...,...,...,...,...,...,...
35544,35545,12,31,2002,15,AH,NaN,NaN,Ecological Archives E090-118-D1
35545,35546,12,31,2002,15,AH,NaN,NaN,Ecological Archives E090-118-D1
35546,35547,12,31,2002,10,RM,F,14.0,Ecological Archives E090-118-D1
35547,35548,12,31,2002,7,DO,M,51.0,Ecological Archives E090-118-D1
35548,35549,12,31,2002,5,NaN,NaN,NaN,Ecological Archives E090-118-D1

In [38]:
surveys_data[ surveys_data['verbatimSex'] == 'P']['sex'] = 'M'

/tmp/ipykernel_828/3204832035.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  surveys_data[ surveys_data['verbatimSex'] == 'P']['sex'] = 'M'

In [11]:
species_data = pd.read_csv('species.csv', sep=';')
species_data

   species_id             genus          species                   taxa
0          AB        Amphispiza        bilineata                   Bird
1          AH  Ammospermophilus          harrisi    Rodent-not censused
2          AS        Ammodramus       savannarum                   Bird
3          BA           Baiomys          taylori                 Rodent
4          CB   Campylorhynchus  brunneicapillus                   Bird
5          CM       Calamospiza      melanocorys                   Bird
6          CQ        Callipepla         squamata                   Bird
7          CS          Crotalus       scutalatus                Reptile
8          CT     Cnemidophorus           tigris                Reptile
9          CU     Cnemidophorus        uniparens                Reptile
10         CV          Crotalus          viridis                Reptile
11         DM         Dipodomys         merriami                 Rodent
12         DO         Dipodomys            ordii                 Rodent
13         DS         Dipodomys      spectabilis                 Rodent
14         DX         Dipodomys              sp.                 Rodent
15         EO           Eumeces        obsoletus                Reptile
16         GS          Gambelia            silus                Reptile
17         NE           Neotoma         albigula                 Rodent
18         NX           Neotoma              sp.                 Rodent
19         OL         Onychomys      leucogaster                 Rodent
20         OT         Onychomys         torridus                 Rodent
21         OX         Onychomys              sp.                 Rodent
22         PB       Chaetodipus          baileyi                 Rodent
23         PC            Pipilo        chlorurus                   Bird
24         PE        Peromyscus         eremicus                 Rodent
25         PF       Perognathus           flavus                 Rodent
26         PG         Pooecetes        gramineus                   Bird
27         PH       Perognathus         hispidus                 Rodent
28         PI       Chaetodipus      intermedius                 Rodent
29         PL        Peromyscus         leucopus                 Rodent
30         PM        Peromyscus      maniculatus                 Rodent
31         PP       Chaetodipus     penicillatus                 Rodent
32         PU            Pipilo           fuscus                   Bird
33         PX       Chaetodipus              sp.                 Rodent
34         RF   Reithrodontomys       fulvescens                 Rodent
35         RM   Reithrodontomys        megalotis                 Rodent
36         RO   Reithrodontomys         montanus                 Rodent
37         RX   Reithrodontomys              sp.                 Rodent
38         SA        Sylvilagus        audubonii                 Rabbit
39         SB          Spizella          breweri                   Bird
40         SC        Sceloporus           clarki                Reptile
41         SF          Sigmodon      fulviventer                 Rodent
42         SH          Sigmodon         hispidus                 Rodent
43         SO          Sigmodon     ochrognathus                 Rodent
44         SS      Spermophilus        spilosoma    Rodent-not censused
45         ST      Spermophilus     tereticaudus    Rodent-not censused
46         SU        Sceloporus        undulatus                Reptile
47         SX          Sigmodon              sp.                 Rodent
48         UL            Lizard              sp.                Reptile
49         UP            Pipilo              sp.                   Bird
50         UR            Rodent              sp.                 Rodent
51         US           Sparrow              sp.                   Bird
52         XX               NaN              NaN  Zero Trapping Success
53         ZL       Zonotrichia       leucophrys                   Bird
54         ZM           Zenaida         macroura                   Bird

In [12]:
plot_data = pd.read_excel('plot_location.xlsx')
plot_data

,Coordinates Ecological Archives E090-118-D1,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,http://esapubs.org/archive/ecol/E090/118/Porta...,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,plot,xutm,yutm
3,0,1,681222.131658,3535262.123799
4,1,2,681302.799361,3535267.545114
5,2,3,681375.294968,3535269.82783
6,3,4,681450.837525,3535270.945141
7,4,5,681526.98304,3535280.724209
8,5,6,681599.189293,3535293.982875
9,6,7,681224.809581,3535180.324306
10,7,8,681332.659397,3535156.837694
11,8,9,681406.168037,3535155.367799
12,9,10,681482.62594,3535174.246131
13,10,11,681556.670465,3535179.884674
14,11,12,681630.880607,3535197.504322
15,12,13,681246.131957,3535060.371412
16,13,14,681320.391953,3535064.570254
17,14,15,681395.165904,3535066.449768
18,15,16,681469.97543,3535071.657575
19,16,17,681548.306618,3535075.597555
20,17,18,681622.221792,3535077.907115
21,18,19,681689.773453,3535113.708144
22,19,20,681476.480274,3534987.486013
23,20,21,681551.229556,3535001.454715
24,21,22,681626.500362,3535002.013856
25,22,23,681698.098229,3535038.99575
26,23,24,681704.204436,3535238.39863